import { ArrowRight, BookOpen, CalendarDays, Check, ChefHat, Lightbulb, ListChecks, Menu, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import './landing-page.css'

const loginUrl = '/?login=1'

function Brand() {
  return <a className="lp-brand" href="#top" aria-label="KitchenOS — strona główna"><span className="lp-brand-icon"><ChefHat size={22} strokeWidth={2.2} /></span><span>kitchen<span className="lp-brand-accent">OS</span></span></a>
}

function Preview() {
  return <div className="lp-preview" aria-label="Podgląd planera KitchenOS">
    <div className="lp-preview-top"><div className="lp-preview-brand"><ChefHat size={17} /> kitchenOS</div><div className="lp-preview-dots"><i/><i/><i/></div></div>
    <div className="lp-preview-body"><div className="lp-preview-side"><span className="active">◫</span><span>▤</span><span>▦</span><span>☷</span></div><div className="lp-preview-content"><div className="lp-preview-heading"><div><small>TWÓJ PLAN POSIŁKÓW</small><h3>Smaczny tydzień zaczyna się tutaj.</h3></div><span className="lp-preview-date">◀ &nbsp; Ten tydzień &nbsp; ▶</span></div><div className="lp-preview-grid"><div className="lp-day"><small>PONIEDZIAŁEK</small><div className="lp-meal-photo meal-one">🥗</div><b>Sałatka z pieczonym batatem</b><span>Obiad · 30 min</span></div><div className="lp-day"><small>WTOREK</small><div className="lp-meal-photo meal-two">🍝</div><b>Kremowy makaron z pesto</b><span>Obiad · 25 min</span></div><div className="lp-day"><small>ŚRODA</small><div className="lp-meal-photo meal-three">🥘</div><b>Curry z ciecierzycą</b><span>Obiad · 35 min</span></div></div><div className="lp-preview-bottom"><span><Check size={15}/> 3 posiłki zaplanowane</span><strong>Generuj listę zakupów <ArrowRight size={15}/></strong></div></div></div>
  </div>
}

export function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <div className="lp" id="top">
    <header className="lp-header"><div className="lp-container lp-nav"><Brand/><nav className={menuOpen ? 'open' : ''} aria-label="Nawigacja główna"><a onClick={() => setMenuOpen(false)} href="#funkcje">Funkcje</a><a onClick={() => setMenuOpen(false)} href="#jak-to-dziala">Jak to działa</a><a onClick={() => setMenuOpen(false)} href="#faq">FAQ</a><a className="lp-mobile-login" href={loginUrl}>Przejdź do aplikacji <ArrowRight size={17}/></a></nav><a className="lp-nav-cta" href={loginUrl}>Przejdź do aplikacji <ArrowRight size={16}/></a><button className="lp-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Zamknij menu' : 'Otwórz menu'} aria-expanded={menuOpen}>{menuOpen ? <X/> : <Menu/>}</button></div></header>
    <main>
      <section className="lp-hero"><div className="lp-container lp-hero-inner"><div className="lp-hero-copy"><span className="lp-eyebrow"><Sparkles size={14}/> MNIEJ PLANOWANIA, WIĘCEJ PRZYJEMNOŚCI</span><h1>Twoja kuchnia.<br/><em>Wreszcie ogarnięta.</em></h1><p>Przepisy, plan posiłków i lista zakupów w jednym miejscu. KitchenOS pomaga zdecydować, co ugotować, i sprawia, że codzienność smakuje lepiej.</p><div className="lp-hero-actions"><a className="lp-button lp-button-primary" href={loginUrl}>Otwórz KitchenOS <ArrowRight size={18}/></a><a className="lp-text-link" href="#jak-to-dziala">Zobacz, jak to działa <ArrowRight size={16}/></a></div><div className="lp-hero-proof"><span className="lp-proof-icon"><Check size={15}/></span> Od pomysłu na obiad do gotowej listy zakupów</div></div><div className="lp-hero-visual"><div className="lp-orbit orbit-one"/><div className="lp-orbit orbit-two"/><Preview/><div className="lp-float-card lp-float-top"><span>✨</span><div><b>Inspiracja na dziś</b><small>Z tego, co masz w lodówce</small></div></div><div className="lp-float-card lp-float-bottom"><span className="lp-float-check"><Check size={16}/></span><div><b>Lista gotowa!</b><small>Wszystko na jeden tydzień</small></div></div></div></div></section>
      <section className="lp-intro" id="funkcje"><div className="lp-container"><div className="lp-section-head"><span className="lp-kicker">JEDNO MIEJSCE. MNIEJ CHAOSU.</span><h2>Wszystko, czego potrzebujesz<br/>w swojej kuchni.</h2><p>Od pierwszego pomysłu po ostatni produkt na liście. Dobre planowanie może być naprawdę proste.</p></div><div className="lp-features"><article className="lp-feature"><span className="lp-feature-icon mint"><BookOpen/></span><h3>Przepisy pod ręką</h3><p>Gromadź ulubione dania, dodawaj własne przepisy i wracaj do nich, kiedy tylko chcesz.</p><div className="lp-feature-art recipe-art"><div><span>🍲</span><b>Twoje ulubione smaki</b><small>Wszystkie przepisy w jednym miejscu</small></div></div></article><article className="lp-feature"><span className="lp-feature-icon peach"><CalendarDays/></span><h3>Plan, który działa</h3><p>Rozpisz posiłki na cały tydzień i uwolnij głowę od codziennego pytania: „co dziś jemy?”.</p><div className="lp-feature-art calendar-art"><div><small>PON</small><b>🥗</b></div><div><small>WT</small><b>🍝</b></div><div><small>ŚR</small><b>🥘</b></div><div><small>CZW</small><b>➕</b></div></div></article><article className="lp-feature"><span className="lp-feature-icon lavender"><ListChecks/></span><h3>Zakupy bez zgadywania</h3><p>Generuj listę zakupów z zaplanowanych dań. Mniej zapomnianych składników, więcej spokoju.</p><div className="lp-feature-art list-art"><div><span>✓</span> Pomidory <small>500 g</small></div><div><span>✓</span> Makaron <small>1 op.</small></div><div><span>○</span> Świeża bazylia <small>1 pęczek</small></div></div></article></div></div></section>
      <section className="lp-how" id="jak-to-dziala"><div className="lp-container lp-how-grid"><div><span className="lp-kicker">OD POMYSŁU DO TALERZA</span><h2>Gotowanie zaczyna się od dobrego planu.</h2><p className="lp-how-lead">KitchenOS łączy to, co zwykle rozrzucone po notatkach, zakładkach i kartkach na lodówce.</p><div className="lp-steps"><div><span>01</span><div><h3>Wybierz swoje przepisy</h3><p>Przeglądaj zapisane dania lub dodaj coś nowego.</p></div></div><div><span>02</span><div><h3>Zaplanuj tydzień</h3><p>Przypisz posiłki do dni, które Ci pasują.</p></div></div><div><span>03</span><div><h3>Ruszaj na zakupy</h3><p>Wygeneruj listę składników i odhaczaj je po drodze.</p></div></div></div><a className="lp-button lp-button-dark" href={loginUrl}>Zacznij planować <ArrowRight size={18}/></a></div><div className="lp-how-visual"><div className="lp-how-circle"/><div className="lp-how-card"><div className="lp-how-card-top"><span>Twój tydzień</span><span>✦</span></div><div className="lp-how-row"><span>🥗</span><div><b>Poniedziałek</b><small>Sałatka z batatem</small></div><Check size={18}/></div><div className="lp-how-row"><span>🍝</span><div><b>Wtorek</b><small>Makaron z pesto</small></div><Check size={18}/></div><div className="lp-how-row"><span>🥘</span><div><b>Środa</b><small>Curry z ciecierzycą</small></div><Check size={18}/></div><div className="lp-how-card-footer"><ListChecks size={20}/> Lista zakupów aktualizuje się z planem</div></div><div className="lp-how-spark">✳</div></div></div></section>
      <section className="lp-ai"><div className="lp-container lp-ai-inner"><span className="lp-ai-icon"><Lightbulb size={25}/></span><div><span className="lp-kicker">ODROBINA INSPIRACJI</span><h2>Nie wiesz, co ugotować?</h2><p>Powiedz, jakie składniki masz pod ręką. Inspiracje AI pomogą znaleźć pomysł na następny posiłek.</p></div><a href={loginUrl} className="lp-ai-link">Odkryj inspiracje <ArrowRight size={18}/></a></div></section>
      <section className="lp-faq" id="faq"><div className="lp-container lp-faq-grid"><div><span className="lp-kicker">WARTO WIEDZIEĆ</span><h2>Masz pytania?<br/>Mamy odpowiedzi.</h2><p>KitchenOS powstał po to, żeby codzienne gotowanie było łatwiejsze.</p></div><div className="lp-faq-list"><details><summary>Czym jest KitchenOS?<span>+</span></summary><p>To aplikacja, która łączy Twoje przepisy, tygodniowy planer posiłków, listę zakupów i kulinarne inspiracje w jednym miejscu.</p></details><details><summary>Czy mogę dodać własne przepisy?<span>+</span></summary><p>Tak. Możesz zapisywać własne przepisy, przeglądać je i wracać do nich przy układaniu planu.</p></details><details><summary>Jak powstaje lista zakupów?<span>+</span></summary><p>Wybierasz dania do planu, a KitchenOS przygotowuje listę potrzebnych składników na podstawie przepisów.</p></details><details><summary>Czy potrzebuję konta?<span>+</span></summary><p>Tak, do korzystania z aplikacji potrzebne jest konto. Dostęp do nowego konta wymaga aktywacji.</p></details></div></div></section>
      <section className="lp-final"><div className="lp-container lp-final-inner"><div className="lp-final-decoration">✳</div><span className="lp-kicker">DOBRY PLAN SMAKUJE LEPIEJ</span><h2>Zrób miejsce na przyjemność<br/>z gotowania.</h2><p>Twoje przepisy, plan i zakupy czekają w jednym miejscu.</p><a className="lp-button lp-button-light" href={loginUrl}>Przejdź do KitchenOS <ArrowRight size={18}/></a></div></section>
    </main><footer className="lp-footer"><div className="lp-container lp-footer-inner"><Brand/><span>© {new Date().getFullYear()} KitchenOS. Smacznie zorganizowane.</span><a href="/prywatnosc">Prywatność</a><a href="#top">Wróć na górę ↑</a></div></footer>
  </div>
}
